import { Driver, MarkerData } from "@/types/type";

const mockDriversData: Driver[] = [
  {
    id: 1,
    name: "John Doe",
    car_model: "Toyota Camry",
    latitude: 37.7749,
    longitude: -122.4194,
    profile_image_url: "https://randomuser.me/api/portraits/men/1.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?car",
    rating: 4.8,
    price: "25",
  },
  {
    id: 2,
    name: "Jane Smith",
    car_model: "Honda Accord",
    latitude: 34.0522,
    longitude: -118.2437,
    profile_image_url: "https://randomuser.me/api/portraits/women/2.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?honda",
    rating: 4.7,
    price: "30",
  },
  {
    id: 3,
    name: "Mike Johnson",
    car_model: "Tesla Model 3",
    latitude: 40.7128,
    longitude: -74.006,
    profile_image_url: "https://randomuser.me/api/portraits/men/3.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?tesla",
    rating: 4.9,
    price: "40",
  },
  {
    id: 4,
    name: "Emily Davis",
    car_model: "Ford Mustang",
    latitude: 41.8781,
    longitude: -87.6298,
    profile_image_url: "https://randomuser.me/api/portraits/women/4.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?ford",
    rating: 4.6,
    price: "50",
  },
  {
    id: 5,
    name: "Chris Brown",
    car_model: "Chevrolet Malibu",
    latitude: 29.7604,
    longitude: -95.3698,
    profile_image_url: "https://randomuser.me/api/portraits/men/5.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?chevrolet",
    rating: 4.5,
    price: "80",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    car_model: "BMW X5",
    latitude: 33.4484,
    longitude: -112.074,
    profile_image_url: "https://randomuser.me/api/portraits/women/6.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?bmw",
    rating: 4.8,
    price: "60",
  },
  {
    id: 7,
    name: "David Martinez",
    car_model: "Mercedes-Benz C-Class",
    latitude: 47.6062,
    longitude: -122.3321,
    profile_image_url: "https://randomuser.me/api/portraits/men/7.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?mercedes",
    rating: 4.7,
    price: "55",
  },
  {
    id: 8,
    name: "Olivia Taylor",
    car_model: "Audi A4",
    latitude: 39.7392,
    longitude: -104.9903,
    profile_image_url: "https://randomuser.me/api/portraits/women/8.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?audi",
    rating: 4.9,
    price: "65",
  },
  {
    id: 9,
    name: "James Anderson",
    car_model: "Lexus RX",
    latitude: 32.7767,
    longitude: -96.797,
    profile_image_url: "https://randomuser.me/api/portraits/men/9.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?lexus",
    rating: 4.6,
    price: "70",
  },
  {
    id: 10,
    name: "Sophia White",
    car_model: "Subaru Outback",
    latitude: 38.9072,
    longitude: -77.0369,
    profile_image_url: "https://randomuser.me/api/portraits/women/10.jpg",
    car_image_url: "https://source.unsplash.com/400x300/?subaru",
    rating: 4.7,
    price: "35",
  },
];

export default mockDriversData;
